SELECT ?prohibition
WHERE {
  ?prohibition a cco:Prohibition ;
               cco:hasAction abox:Action1 ;
               cco:hasObject abox:Resource1 ;
               cco:appliesUnder ?condition ;
               cco:hasException ?exception .
  ?condition cco:hasConditionExpression "fund an apprentice working under IR35"^^xsd:string .
  ?exception cco:hasCondition ?exceptionCondition .
  ?exceptionCondition cco:hasConditionExpression "meet alternative arrangements"^^xsd:string .
}